rotas:
  pfa_home:                       app\controllers\monitoramento\PFAcontroller
  pfa_provas:                     app\controllers\monitoramento\PFAcontroller
  pfa_prova:                      app\controllers\monitoramento\PFAcontroller
  validar_login_pfa:              app\controllers\monitoramento\PFAcontroller
  login_adm_verifica:             app\controllers\monitoramento\AdmController
  adm_home:                       app\controllers\monitoramento\AdmController
  adicionar_aluno:                app\controllers\monitoramento\AdmController
  editar_dados_aluno:             app\controllers\monitoramento\AdmController
  adm_info:                       app\controllers\monitoramento\AdmController
  home:                           app\controllers\monitoramento\MainController
  adm:                            app\controllers\monitoramento\MainController
  ADM:                            app\controllers\monitoramento\MainController
  login_pfa:                      app\controllers\monitoramento\MainController
  login_professor:                app\controllers\monitoramento\MainController
  login_gestor:                   app\controllers\monitoramento\MainController
  index:                          app\controllers\monitoramento\MainController
  login_adm:                      app\controllers\monitoramento\MainController
  encerrar_sessao:                app\controllers\monitoramento\MainController
  aluno_home:                     app\controllers\monitoramento\AlunoController
  login_aluno_entrar:             app\controllers\monitoramento\AlunoController
  cadastrar_gabarito_aluno:       app\controllers\monitoramento\AlunoController
  cadastrar_gabarito_aluno_rec:   app\controllers\monitoramento\AlunoController
  gabarito_aluno:                 app\controllers\monitoramento\AlunoController
  gabarito_aluno_rec:             app\controllers\monitoramento\AlunoController
  gestor_home:                    app\controllers\monitoramento\GestorController
  gestor_descritores:             app\controllers\monitoramento\GestorController
  gestor_provas:                  app\controllers\monitoramento\GestorController
  gestor_prova:                   app\controllers\monitoramento\GestorController
  login_gestor_verifica:          app\controllers\monitoramento\GestorController
  home_professor:                 app\controllers\monitoramento\ProfessorController
  professor_home:                 app\controllers\monitoramento\ProfessorController
  inserir_gabarito:               app\controllers\monitoramento\ProfessorController
  ver_provas:                     app\controllers\monitoramento\ProfessorController
  prova:                          app\controllers\monitoramento\ProfessorController
  criar_gabarito:                 app\controllers\monitoramento\ProfessorController
  atualizar_gabarito:             app\controllers\monitoramento\ProfessorController
  editar_prova:                   app\controllers\monitoramento\ProfessorController
  relatorio_professor:            app\controllers\monitoramento\ProfessorController
  relatorio_prova:                app\controllers\monitoramento\ProfessorController
  add_recuperacao:                app\controllers\monitoramento\ProfessorController
  criar_gabarito_respostas:       app\controllers\monitoramento\ProfessorController
  inserir_gabarito_rec:           app\controllers\monitoramento\ProfessorController
  criar_gabarito_rec:             app\controllers\monitoramento\ProfessorController
  criar_gabarito_rec_resp:        app\controllers\monitoramento\ProfessorController
  prova_recuperacao:              app\controllers\monitoramento\ProfessorController
  editar_gabarito_recuperacao:    app\controllers\monitoramento\ProfessorController
  atualizar_gabarito_rec:         app\controllers\monitoramento\ProfessorController
  professor_security:             app\controllers\monitoramento\ProfessorController
  download_gabarito:       app\controllers\monitoramento\ProfessorController
  lancar_gabarito:         app\controllers\monitoramento\ProfessorController
  capturar_gabarito:       app\controllers\monitoramento\ProfessorController
  salvar_gabarito:         app\controllers\monitoramento\ProfessorController
  simulados:               app\controllers\monitoramento\GestorController
  criar_simulado:          app\controllers\monitoramento\GestorController
  editar_simulado:         app\controllers\monitoramento\GestorController
  excluir_simulado:        app\controllers\monitoramento\GestorController
  download_multi_gabarito: app\controllers\monitoramento\GestorController
